version: "3.3"
services:
  app:
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ../.
      args:
        VARIANT: "14"
    ports:
      - "127.0.0.1:9222:9222"
    links:
      - postgres
    volumes:
      - ../.:/workspace:cached
  postgres:
    image: postgres:latest
    volumes:
      - postgresvol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myjam
      - POSTGRES_PASSWORD=myjam
      - POSTGRES_DB:myjam 
    ports:
      - "5432:5432"
volumes:
  postgresvol:
    external: false
